-- MySQL Script generated by MySQL Workbench
-- 08/28/16 19:53:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema unisus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unisus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unisus` DEFAULT CHARACTER SET utf8 ;
USE `unisus` ;

-- -----------------------------------------------------
-- Table `unisus`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unisus`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idlogin_UNIQUE` ON `unisus`.`login` (`idlogin` ASC);

CREATE UNIQUE INDEX `nome_usuario_UNIQUE` ON `unisus`.`login` (`nome_usuario` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
