-- MySQL Script generated by MySQL Workbench
-- 08/28/16 20:35:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema unisus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unisus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unisus` DEFAULT CHARACTER SET utf8 ;
USE `unisus` ;

-- -----------------------------------------------------
-- Table `unisus`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unisus`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlogin`),
  UNIQUE INDEX `idlogin_UNIQUE` (`idlogin` ASC),
  UNIQUE INDEX `nome_usuario_UNIQUE` (`nome_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unisus`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unisus`.`endereco` (
  `idendereco` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NULL,
  `complemento` VARCHAR(255) NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unisus`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unisus`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `login_idlogin` INT NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_usuario_login_idx` (`login_idlogin` ASC),
  INDEX `fk_usuario_endereco1_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_usuario_login`
    FOREIGN KEY (`login_idlogin`)
    REFERENCES `unisus`.`login` (`idlogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_endereco1`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `unisus`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unisus`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unisus`.`telefones` (
  `idtelefones` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(12) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idtelefones`, `usuario_idusuario`),
  UNIQUE INDEX `idtelefones_UNIQUE` (`idtelefones` ASC),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC),
  INDEX `fk_telefones_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_telefones_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `unisus`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
